# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Dmitry Petrov
url:              http://can3p.github.io
paginate:         1
baseurl:          /
author:
  name:           Dmitry Petrov
  url:            https://can3p.github.io
  email:          dpetroff@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
