# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dmitry Petrov
url:              https://can3p.github.io
paginate:         1
baseurl:          ""
description:     "Rants about programming - javascript, clojure and friends"
keywords:        "html, javascript, clojure, programming"
author:
  name:           Dmitry Petrov
  url:            https://can3p.github.io
  email:          dpetroff@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole

gems: [jekyll-paginate, jekyll-sitemap]
